trigger: none
 
pool:
  name: ccoe-nprod-windows-mdp-01
 
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
 
steps:
  # Step 1: Install NuGet tool
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet Tool'

  # Step 2: Authenticate to NuGet feeds
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate NuGet Feeds'

  # Step 3: Create nuget.config for private and public feeds
  - task: PowerShell@2
    displayName: 'Configure NuGet Feeds'
    inputs:
      targetType: 'inline'
      script: |
        $nugetConfig = @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="Boots.Common" value="https://pkgs.dev.azure.com/BootsCCoE/Masterdata/_packaging/Boots.Common/nuget/v3/index.json" />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
          </packageSources>
          <packageSourceCredentials>
            <Boots.Common>
              <add key="Username" value="PAT" />
              <add key="ClearTextPassword" value="$(System.AccessToken)" />
            </Boots.Common>
          </packageSourceCredentials>
        </configuration>
        "@
        Set-Content -Path "$(Build.SourcesDirectory)\nuget.config" -Value $nugetConfig
        Write-Host "nuget.config created successfully"
        Get-Content -Path "$(Build.SourcesDirectory)\nuget.config"

  # Step 4: Restore NuGet packages
  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\nuget.config'

  # Step 5: Build the solution
  - task: VSBuild@1
    displayName: 'Build Solution'
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/t:Rebuild'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
 
  # Step 6: Install Visual Studio Test Platform
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Install VS Test Platform'
    inputs:
      packageFeedSelector: 'nugetOrg'
 
  # Step 7: Archive AutoDataRefresh
  - task: ArchiveFiles@2
    displayName: 'Archive AutoDataRefresh'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/Application Layer/Boots.MasterData.Application.AutoDataRefresh/bin/Release'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/Boots.MasterData.Application.AutoDataRefresh.zip'
      replaceExistingArchive: true
 
  # Step 8: Publish AutoDataRefresh artifact
  - publish: '$(Build.ArtifactStagingDirectory)/Boots.MasterData.Application.AutoDataRefresh.zip'
    displayName: 'Publish AutoDataRefresh.zip'
    artifact: AutoDataRefresh