parameters:
  - name: dataLoadSlot
    displayName: Target SIT DataLoad slot
    type: string
    default: SIT_IT1_Dataload
    values:
      - SIT_IT1_Dataload
      - SIT_IT2_Dataload
      - SIT_IT3_Dataload

pool:
  name: ccoe-nprod-windows-mdp-01

trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: MasterData.DB.DataLoad

variables:
  - ${{ if eq(parameters.dataLoadSlot, 'SIT_IT1_Dataload') }}:
      - group: SIT_IT1_Dataload
      - name: destinationFolder
        value: 'G:\MasterData\DataLoad\IT1_SIT_Dataload'
  - ${{ if eq(parameters.dataLoadSlot, 'SIT_IT2_Dataload') }}:
      - group: SIT_IT2_Dataload
      - name: destinationFolder
        value: 'G:\MasterData\DataLoad\IT2_SIT_Dataload'
  - ${{ if eq(parameters.dataLoadSlot, 'SIT_IT3_Dataload') }}:
      - group: SIT_IT3_Dataload
      - name: destinationFolder
        value: 'G:\MasterData\DataLoad\IT3_SIT_Dataload'

stages:
  - stage: Deploy_SIT
    displayName: Deploy to SIT VM
    jobs:
      - deployment: DeployDataLoad
        displayName: Deploy DataLoad zip
        environment:
          name: SIT
          resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - download: buildPipeline
                  displayName: Download latest DataLoad artifact
                  artifact: drop

                - task: PowerShell@2
                  displayName: Check AlwaysOn Primary Node
                  inputs:
                    targetType: inline
                    script: |
                      $alwaysOn = "$(Server_AlwaysOn_Enabled)"
                      $currentMachineName = $env:COMPUTERNAME
                      $alwaysOnClusterInstance = "$(Server_DB_Instance_Name)"
                      
                      Write-Host "AlwaysOn Enabled: $alwaysOn"
                      Write-Host "Current Machine Name: $currentMachineName"
                      
                      if ($alwaysOn -eq "false") {
                          Write-Host "AlwaysOn is disabled. Proceeding with deployment."
                          exit 0
                      }
                      
                      # Connect to SQL Server and check primary node
                      $serverName = "$(Server_DB_Local_Instance)"
                      $sqlLogin = "$(Server_DB_Admin_User)"
                      $sqlPassword = "$(Server_DB_Admin_Password)"
                      
                      Write-Host "Connecting to SQL Server: $serverName"
                      
                      # Load SQL Server SMO assemblies
                      [System.Reflection.Assembly]::LoadWithPartialName("Microsoft.SqlServer.SMO") | Out-Null
                      [System.Reflection.Assembly]::LoadWithPartialName("Microsoft.SqlServer.SmoExtended") | Out-Null
                      [System.Reflection.Assembly]::LoadWithPartialName("Microsoft.SqlServer.ConnectionInfo") | Out-Null
                      [System.Reflection.Assembly]::LoadWithPartialName("Microsoft.SqlServer.SmoEnum") | Out-Null
                      
                      $server = New-Object Microsoft.SqlServer.Management.Smo.Server $serverName
                      
                      if ($sqlLogin -ne $null -and $sqlLogin -ne "") {
                          if ($sqlPassword -eq $null -or $sqlPassword -eq "") {
                              throw "SQL Password must be specified when using SQL authentication."
                          }
                          Write-Host "Connecting to server using SQL authentication as $sqlLogin."
                          $server.ConnectionContext.LoginSecure = $false
                          $server.ConnectionContext.Login = $sqlLogin
                          $server.ConnectionContext.Password = $sqlPassword
                          $server = New-Object Microsoft.SqlServer.Management.Smo.Server $server.ConnectionContext
                      }
                      else {
                          Write-Host "Connecting to server using Windows authentication."
                      }
                      
                      try {
                          $server.ConnectionContext.Connect()
                          Write-Host "Connected to server."
                      }
                      catch {
                          Write-Error "An error occurred connecting to the database server!`r`n$($_.Exception.ToString())"
                          exit 1
                      }
                      
                      # Query AlwaysOn cluster for primary node
                      try {
                          Write-Host "Attempting to discover primary node from AlwaysOn cluster"
                          $masterDB = $server.Databases["master"]
                          $alwaysOnQuery = "SELECT TOP 1 hags.primary_replica FROM sys.dm_hadr_availability_group_states hags INNER JOIN sys.availability_groups ag ON ag.group_id = hags.group_id WHERE ag.name = '$alwaysOnClusterInstance';"
                          $ds = $masterDB.ExecuteWithResults($alwaysOnQuery)
                          $primaryNode = ""
                          
                          foreach ($t in $ds.Tables) {
                              foreach ($r in $t.Rows) {
                                  foreach ($c in $t.Columns) {
                                      $primaryNode = $r.Item($c)
                                  }
                              }
                          }
                          
                          Write-Host "Primary host is: $primaryNode"
                          Write-Host "Current Machine is: $currentMachineName"
                          
                          if ($currentMachineName -like "*$primaryNode*") {
                              Write-Host "Current machine matches primary node. Proceeding with deployment."
                              exit 0
                          }
                          else {
                              Write-Error "Current machine ($currentMachineName) is not the primary AlwaysOn node ($primaryNode). Deployment cannot proceed."
                              exit 1
                          }
                      }
                      catch {
                          Write-Error "Failed to query AlwaysOn cluster: $($_.Exception.Message)"
                          echo $_.Exception | Format-List -Force
                          exit 1
                      }

                - task: PowerShell@2
                  displayName: Extract MasterData.DB.DataLoad.zip to destination folder
                  inputs:
                    targetType: inline
                    script: |
                      $destination = "$(destinationFolder)"
                      $artifactRoot = "$(Pipeline.Workspace)\buildPipeline\drop"
                      $zipPath = Join-Path $artifactRoot 'MasterData.DB.DataLoad.zip'

                      if (-not (Test-Path $zipPath)) {
                        Write-Error "Artifact zip not found at $zipPath"
                      }

                      if (-not (Test-Path $destination)) {
                        Write-Host "Creating destination folder $destination"
                        New-Item -ItemType Directory -Path $destination | Out-Null
                      } else {
                        Write-Host "Clearing existing contents in $destination"
                        Get-ChildItem -Path $destination -Recurse -Force | Remove-Item -Recurse -Force
                      }

                      Write-Host "Extracting $zipPath to $destination"
                      Expand-Archive -LiteralPath $zipPath -DestinationPath $destination -Force

