parameters:
  - name: userSlot
    displayName: Target SIT user slot
    type: string
    default: SIT_IT1_ADR
    values:
      - SIT_IT1_ADR
      - SIT_IT2_ADR
      - SIT_IT3_ADR
      - SIT_IT4_ADR

pool:
  name: ccoe-nprod-windows-mdp-01

trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: MasterData.AutoDataRefresh

variables:
  - ${{ if eq(parameters.userSlot, 'SIT_IT1_ADR') }}:
      - group: SIT_IT1_ADR
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\IT1_SIT_ADR'
  - ${{ if eq(parameters.userSlot, 'SIT_IT2_ADR') }}:
      - group: SIT_IT2_ADR
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\IT2_SIT_ADR'
  - ${{ if eq(parameters.userSlot, 'SIT_IT3_ADR') }}:
      - group: SIT_IT3_ADR
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\IT3_SIT_ADR'
  - ${{ if eq(parameters.userSlot, 'SIT_IT4_ADR') }}:
      - group: SIT_IT4_ADR
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\IT4_SIT_ADR'

stages:
  - stage: Deploy_SIT
    displayName: Deploy to SIT VM
    jobs:
      - deployment: DeployAutoDataRefresh
        displayName: Deploy AutoDataRefresh zip
        environment:
          name: SIT
          resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - download: buildPipeline
                  displayName: Download latest AutoDataRefresh artifact
                  artifact: AutoDataRefresh

                - task: PowerShell@2
                  displayName: Extract AutoDataRefresh.zip to destination folder
                  inputs:
                    targetType: inline
                    script: |
                      $destination = "$(destinationFolder)"
                      $artifactRoot = "$(Pipeline.Workspace)\buildPipeline\AutoDataRefresh"
                      $zipPath = Join-Path $artifactRoot 'Boots.MasterData.Application.AutoDataRefresh.zip'

                      if (-not (Test-Path $zipPath)) {
                        Write-Error "Artifact zip not found at $zipPath"
                      }

                      if (-not (Test-Path $destination)) {
                        Write-Host "Creating destination folder $destination"
                        New-Item -ItemType Directory -Path $destination | Out-Null
                      } else {
                        Write-Host "Clearing existing contents in $destination"
                        Get-ChildItem -Path $destination -Recurse -Force | Remove-Item -Recurse -Force
                      }

                      Write-Host "Extracting $zipPath to $destination"
                      Expand-Archive -LiteralPath $zipPath -DestinationPath $destination -Force


                - task: FileTransform@1
                  displayName: Apply SIT-specific variables to config
                  inputs:
                    folderPath: '$(destinationFolder)'
                    fileType: xml
                    targetFiles: 'Boots.MasterData.Application.AutoDataRefresh.exe.config'
