trigger:
- none

# Runtime parameters for version numbers (same pattern as main_CI)
parameters:
  - name: AssemblyVersionNumber
    displayName: 'Assembly Version Number (for breaking changes)'
    type: string
    default: '1'
  - name: BuildVersionNumber
    displayName: 'Build Version Number (for new features)'
    type: string
    default: '0'

pool:
  name: ccoe-nprod-windows-mdp-01

variables:
  - group: Assembly_Build_Version
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: versionNumber
    value: '${{ parameters.AssemblyVersionNumber }}.${{ parameters.BuildVersionNumber }}.$(Build.BuildId)'

# Set build number format
name: '${{ parameters.AssemblyVersionNumber }}.${{ parameters.BuildVersionNumber }}-$(Build.BuildId)'

steps:
- task: PowerShell@2
  displayName: 'Compute Build Version'
  inputs:
    targetType: 'inline'
    script: |
      $major = "${{ parameters.AssemblyVersionNumber }}"
      $minor = "${{ parameters.BuildVersionNumber }}"
      $buildId = [int]$(Build.BuildId)
      $assemblyBuild = $buildId % 65535
      $assemblyVersion = "$major.$minor.$assemblyBuild.0"

      Write-Host "##vso[task.setvariable variable=assemblyVersion]$assemblyVersion"
      Write-Host "Package Version: $(versionNumber)"
      Write-Host "Assembly Version: $assemblyVersion"
      Write-Host "Build Number: $(Build.BuildNumber)"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=false /p:Version=$(versionNumber) /p:AssemblyVersion=$(assemblyVersion) /p:FileVersion=$(assemblyVersion)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
 
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'



- task: ArchiveFiles@2
  displayName: 'Archive MasterData.DB.InitialStagingDB'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Boots.MasterData.DB.InitialStagingDB/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.DB.InitialStagingDB.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  displayName: 'Archive MasterData.DB.ManualUpgrade'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Boots.MasterData.DB.ManualUpgrade/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.DB.ManualUpgrade.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  displayName: 'Archive MasterData.DB.MasterDataCDC'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Boots.MasterData.DB.MasterDataCDC/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.DB.MasterDataCDC.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  displayName: 'Archive MasterData.DB.MasterDataDB'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Boots.MasterData.DB.MasterDataDB/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.DB.MasterDataDB.zip'
    replaceExistingArchive: true
 


- publish: '$(Build.ArtifactStagingDirectory)/MasterData.DB.InitialStagingDB.zip'
  displayName: 'Publish MasterData.DB.InitialStagingDB.zip'
  artifact: MasterData.DB.InitialStagingDB

- publish: '$(Build.ArtifactStagingDirectory)/MasterData.DB.ManualUpgrade.zip'
  displayName: 'Publish MasterData.DB.ManualUpgrade.zip'
  artifact: MasterData.DB.ManualUpgrade

- publish: '$(Build.ArtifactStagingDirectory)/MasterData.DB.MasterDataCDC.zip'
  displayName: 'Publish MasterData.DB.MasterDataCDC.zip'
  artifact: MasterData.DB.MasterDataCDC

- publish: '$(Build.ArtifactStagingDirectory)/MasterData.DB.MasterDataDB.zip'
  displayName: 'Publish MasterData.DB.MasterDataDB.zip'
  artifact: MasterData.DB.MasterDataDB
