trigger: none

# Runtime parameters for version numbers (same pattern as main_CI)
parameters:
  - name: AssemblyVersionNumber
    displayName: 'Assembly Version Number (for breaking changes)'
    type: string
    default: '1'
  - name: BuildVersionNumber
    displayName: 'Build Version Number (for new features)'
    type: string
    default: '0'

pool:
  name: ccoe-nprod-windows-mdp-01

variables:
  - group: Assembly_Build_Version
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: versionNumber
    value: '${{ parameters.AssemblyVersionNumber }}.${{ parameters.BuildVersionNumber }}.$(Build.BuildId)'

# Set build number format
name: '${{ parameters.AssemblyVersionNumber }}.${{ parameters.BuildVersionNumber }}-$(Build.BuildId)'

steps:
- task: PowerShell@2
  displayName: 'Display Build Version'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Building version: $(versionNumber)"
      Write-Host "Build Number: $(Build.BuildNumber)"
      Write-Host "Assembly Version: ${{ parameters.AssemblyVersionNumber }}"
      Write-Host "Build Version: ${{ parameters.BuildVersionNumber }}"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=false /p:Version=$(versionNumber) /p:AssemblyVersion=$(versionNumber) /p:FileVersion=$(versionNumber)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
 
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'

- task: ArchiveFiles@2
  displayName: 'Archive MasterData.DB.DataLoad'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Boots.MasterData.DB.DataLoad/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.DB.DataLoad.zip'
    replaceExistingArchive: true
 
- publish: '$(Build.ArtifactStagingDirectory)/MasterData.DB.DataLoad.zip'
  displayName: 'Publish MasterData.DB.DataLoad.zip'
  artifact: 'drop'
