parameters:
  - name: adrSlot
    displayName: ADR Deployment Slot
    type: string
    default: Dev
    values:
      - Dev
      - FT1
      - FT2
      - FT3
      - R1
      - QA
      - Demo
      - SIT
      - Pre-Prod
      - Production

pool:
  name: ccoe-nprod-windows-mdp-01

trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: MasterData.AutoDataRefresh

variables:
  # Shared server catalog for ADR
  - group: vg-shared-servers

  # Load WinRM service account credentials based on ADR slot
  - ${{ if ne(parameters.adrSlot, 'Production') }}:
      - group: NonProd-WinRM-ServiceAccount
  - ${{ if eq(parameters.adrSlot, 'Production') }}:
      - group: Prod-WinRM-ServiceAccount

  # Load slot-based variable groups for ADR slots
  - ${{ if eq(parameters.adrSlot, 'Dev') }}:
      - group: Development_ADR
  - ${{ if eq(parameters.adrSlot, 'FT1') }}:
      - group: FT1_ADR
  - ${{ if eq(parameters.adrSlot, 'FT2') }}:
      - group: FT2_ADR
  - ${{ if eq(parameters.adrSlot, 'FT3') }}:
      - group: FT3_ADR
  - ${{ if eq(parameters.adrSlot, 'R1') }}:
      - group: R1_ADR
  - ${{ if eq(parameters.adrSlot, 'Demo') }}:
      - group: Demo_ADR
  - ${{ if eq(parameters.adrSlot, 'SIT') }}:
      - group: SIT_ADR
  - ${{ if eq(parameters.adrSlot, 'Pre-Prod') }}:
      - group: Pre-Prod_ADR
  - ${{ if eq(parameters.adrSlot, 'Production') }}:
      - group: Production_ADR

  # Map ADR slot to target servers (from vg-shared-servers)
  # Dev / FT* / R1 / QA / Demo all use the Development app server (RT01)
  - ${{ if eq(parameters.adrSlot, 'Dev') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'FT1') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'FT2') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'FT3') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'R1') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'QA') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'Demo') }}:
      - name: selectedServerName
        value: '$(Development-app-server)'
  - ${{ if eq(parameters.adrSlot, 'SIT') }}:
      - name: selectedServerName
        value: '$(SIT-app-server)'
  - ${{ if eq(parameters.adrSlot, 'Pre-Prod') }}:
      - name: selectedServerName
        value: '$(Pre-prod-app1-server),$(Pre-prod-app2-server)'
  - ${{ if eq(parameters.adrSlot, 'Production') }}:
      - name: selectedServerName
        value: '$(Production-app1-Server),$(Production-app2-Server)'

  # Destination folder per ADR slot (D:\AutoDataRefreshMDUpgrade tree)
  - ${{ if eq(parameters.adrSlot, 'Dev') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_Dev_ADR'
  - ${{ if eq(parameters.adrSlot, 'FT1') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_FT1_ADR'
  - ${{ if eq(parameters.adrSlot, 'FT2') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_FT2_ADR'
  - ${{ if eq(parameters.adrSlot, 'FT3') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_FT3_ADR'
  - ${{ if eq(parameters.adrSlot, 'R1') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_R1_ADR'
  - ${{ if eq(parameters.adrSlot, 'QA') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_QA_ADR'
  - ${{ if eq(parameters.adrSlot, 'Demo') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\ST_Demo_ADR'
  - ${{ if eq(parameters.adrSlot, 'SIT') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\SIT'
  - ${{ if eq(parameters.adrSlot, 'Pre-Prod') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\PreProd'
  - ${{ if eq(parameters.adrSlot, 'Production') }}:
      - name: destinationFolder
        value: 'D:\AutoDataRefreshMDUpgrade\Prod'

stages:
  - stage: Deploy_SIT
    displayName: Deploy to SIT VM
    jobs:
      - job: DeployAutoDataRefresh
        displayName: Deploy AutoDataRefresh zip
        pool:
          name: ccoe-nprod-windows-mdp-01
        steps:
          - download: buildPipeline
            displayName: Download latest AutoDataRefresh artifact
            artifact: AutoDataRefresh

          - task: ExtractFiles@1
            displayName: Extract AutoDataRefresh artifact
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)\buildPipeline\AutoDataRefresh\Boots.MasterData.Application.AutoDataRefresh.zip'
              destinationFolder: '$(Pipeline.Workspace)\temp_managed'
              cleanDestinationFolder: true

          - task: FileTransform@1
            displayName: Transform configuration files
            inputs:
              folderPath: '$(Pipeline.Workspace)\temp_managed'
              fileType: "xml"
              targetFiles: "**/Boots.MasterData.Application.AutoDataRefresh.exe.config"

          - task: ArchiveFiles@2
            displayName: Re-zip transformed artifact
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)\temp_managed'
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: '$(Pipeline.Workspace)\buildPipeline\AutoDataRefresh\Boots.MasterData.Application.AutoDataRefresh.zip'
              replaceExistingArchive: true

          - task: WindowsMachineFileCopy@2
            displayName: Copy AutoDataRefresh.zip to target server
            inputs:
              SourcePath: '$(Pipeline.Workspace)\buildPipeline\AutoDataRefresh\Boots.MasterData.Application.AutoDataRefresh.zip'
              MachineNames: "$(selectedServerName)"
              AdminUserName: "$(winrmUserName)"
              AdminPassword: "$(winrmPassword)"
              TargetPath: 'C:\Temp\AutoDataRefresh'
              Protocol: "WinRM"

          - task: PowerShellOnTargetMachines@3
            displayName: Extract AutoDataRefresh on target server
            inputs:
              Machines: "$(selectedServerName)"
              UserName: "$(winrmUserName)"
              UserPassword: "$(winrmPassword)"
              InlineScript: |
                $destination = "$(destinationFolder)"
                $tempFolder = 'C:\Temp\AutoDataRefresh'
                $zipPath = Join-Path $tempFolder 'Boots.MasterData.Application.AutoDataRefresh.zip'

                Write-Host "Checking for zip file at: $zipPath"
                if (-not (Test-Path $zipPath)) {
                  Write-Host "ERROR: Zip file not found at $zipPath"
                  if (Test-Path $tempFolder) {
                    Write-Host "Temp folder contents:"
                    Get-ChildItem -Path $tempFolder -Recurse | ForEach-Object { Write-Host "  - $($_.FullName)" }
                  }
                  throw "Artifact zip not found at $zipPath"
                }
                Write-Host "Zip file found successfully at $zipPath"

                if (-not (Test-Path $destination)) {
                  Write-Host "Creating destination folder $destination"
                  New-Item -ItemType Directory -Path $destination -Force | Out-Null
                } else {
                  Write-Host "Clearing existing contents in $destination"
                  Get-ChildItem -Path $destination -Recurse -Force | Remove-Item -Recurse -Force
                }

                Write-Host "Extracting $zipPath to $destination"
                Expand-Archive -LiteralPath $zipPath -DestinationPath $destination -Force
                Write-Host "Extraction completed successfully"
              NewPsSessionOptionArguments: >
                -SkipCACheck
                -SkipCNCheck
                -SkipRevocationCheck
                -IdleTimeout 7200000
                -OperationTimeout 0
                -OutputBufferingMode Block
