parameters:
  - name: environment
    displayName: Environment
    type: string
    default: non-prod
    values:
      - non-prod
      - prod

  - name: prodServerName
    displayName: Production Server
    type: string
    default: GBRPMSMDFT01.Corp.Internal
    values:
      - GBRPMSMDFT01.Corp.Internal
      - GBRPMSMDRT01.Corp.Internal
      - GBRPMSMDST03.Corp.Internal

  - name: nonProdServerName
    displayName: Non-Production Server
    type: string
    default: GBRPMSMDFT01.Corp.Internal
    values:
      - GBRPMSMDFT01.Corp.Internal
      - GBRPMSMDRT01.Corp.Internal
      - GBRPMSMDST03.Corp.Internal

  - name: userSlot
    displayName: Target user slot
    type: string
    default: ST_Dev_ADR
    values:
      - ST_Dev_ADR
      - ST_FT1_ADR
      - ST_FT2_ADR
      - ST_FT3_ADR
      - ST_R1_ADR

pool:
  name: ccoe-nprod-windows-mdp-01

trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: MasterData.AutoDataRefresh

variables:
  # Set server name based on environment parameter
  - ${{ if eq(parameters.environment, 'prod') }}:
      - name: selectedServerName
        value: ${{ parameters.prodServerName }}
  - ${{ if eq(parameters.environment, 'non-prod') }}:
      - name: selectedServerName
        value: ${{ parameters.nonProdServerName }}

  # Load WinRM service account credentials based on environment parameter
  - ${{ if eq(parameters.environment, 'non-prod') }}:
      - group: NonProd-WinRM-ServiceAccount
  - ${{ if eq(parameters.environment, 'prod') }}:
      - group: Prod-WinRM-ServiceAccount

  # Load userSlot-based variable groups
  - ${{ if eq(parameters.userSlot, 'ST_Dev_ADR') }}:
      - group: ST_Dev_ADR
  - ${{ if eq(parameters.userSlot, 'ST_FT1_ADR') }}:
      - group: ST_FT1_ADR
  - ${{ if eq(parameters.userSlot, 'ST_FT2_ADR') }}:
      - group: ST_FT2_ADR
  - ${{ if eq(parameters.userSlot, 'ST_FT3_ADR') }}:
      - group: ST_FT3_ADR
  - ${{ if eq(parameters.userSlot, 'ST_R1_ADR') }}:
      - group: ST_R1_ADR

  # Set destination folder based on userSlot
  - ${{ if eq(parameters.userSlot, 'ST_Dev_ADR') }}:
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\ST_Dev_ADR'
  - ${{ if eq(parameters.userSlot, 'ST_FT1_ADR') }}:
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\ST_FT1_ADR'
  - ${{ if eq(parameters.userSlot, 'ST_FT2_ADR') }}:
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\ST_FT2_ADR'
  - ${{ if eq(parameters.userSlot, 'ST_FT3_ADR') }}:
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\ST_FT3_ADR'
  - ${{ if eq(parameters.userSlot, 'ST_R1_ADR') }}:
      - name: destinationFolder
        value: 'G:\MasterData\AutoDataRefresh\ST_R1_ADR'

stages:
  - stage: Deploy_SIT
    displayName: Deploy to SIT VM
    jobs:
      - job: DeployAutoDataRefresh
        displayName: Deploy AutoDataRefresh zip
        pool:
          name: ccoe-nprod-windows-mdp-01
        steps:
          - download: buildPipeline
            displayName: Download latest AutoDataRefresh artifact
            artifact: AutoDataRefresh

          - task: PowerShellOnTargetMachines@3
            displayName: Copy and extract AutoDataRefresh on target server
            inputs:
              Machines: "$(selectedServerName)"
              UserName: "$(winrmUserName)"
              UserPassword: "$(winrmPassword)"
              CopyFilesToMachines: |
                $(Pipeline.Workspace)\buildPipeline\AutoDataRefresh\Boots.MasterData.Application.AutoDataRefresh.zip => C:\Temp\AutoDataRefresh\
              InlineScript: |
                $destination = "$(destinationFolder)"
                $tempFolder = 'C:\Temp\AutoDataRefresh'
                $zipPath = Join-Path $tempFolder 'Boots.MasterData.Application.AutoDataRefresh.zip'

                if (-not (Test-Path $zipPath)) {
                  throw "Artifact zip not found at $zipPath"
                }

                if (-not (Test-Path $destination)) {
                  Write-Host "Creating destination folder $destination"
                  New-Item -ItemType Directory -Path $destination -Force | Out-Null
                } else {
                  Write-Host "Clearing existing contents in $destination"
                  Get-ChildItem -Path $destination -Recurse -Force | Remove-Item -Recurse -Force
                }

                Write-Host "Extracting $zipPath to $destination"
                Expand-Archive -LiteralPath $zipPath -DestinationPath $destination -Force
                Write-Host "Extraction completed successfully"
              NewPsSessionOptionArguments: >
                -SkipCACheck
                -SkipCNCheck
                -SkipRevocationCheck
                -IdleTimeout 7200000
                -OperationTimeout 0
                -OutputBufferingMode Block

          - task: PowerShellOnTargetMachines@3
            displayName: Apply configuration transformations
            inputs:
              Machines: "$(selectedServerName)"
              UserName: "$(winrmUserName)"
              UserPassword: "$(winrmPassword)"
              InlineScript: |
                $configPath = Join-Path "$(destinationFolder)" "Boots.MasterData.Application.AutoDataRefresh.exe.config"
                if (Test-Path $configPath) {
                  Write-Host "Configuration file found at $configPath"
                  # FileTransform variables will be applied if configured in variable groups
                } else {
                  Write-Warning "Configuration file not found at $configPath"
                }
              NewPsSessionOptionArguments: >
                -SkipCACheck
                -SkipCNCheck
                -SkipRevocationCheck
                -IdleTimeout 7200000
                -OperationTimeout 0
                -OutputBufferingMode Block