trigger:
- MDVersionUpgrade/Lonestar

# Runtime parameters for version numbers
parameters:
  - name: AssemblyVersionNumber
    displayName: 'Assembly Version Number (for breaking changes)'
    type: string
    default: '1'
  - name: BuildVersionNumber
    displayName: 'Build Version Number (for new features)'
    type: string
    default: '0'
 
pool:
  name: ccoe-nprod-windows-mdp-01
 
variables:
  - group: Assembly_Build_Version
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: versionNumber
    value: '${{ parameters.AssemblyVersionNumber }}.${{ parameters.BuildVersionNumber }}.$(Build.BuildId)'

# Set build number format
name: '${{ parameters.AssemblyVersionNumber }}.${{ parameters.BuildVersionNumber }}-$(Build.BuildId)'
 
steps:
- task: PowerShell@2
  displayName: 'Compute Build Version'
  inputs:
    targetType: 'inline'
    script: |
      $major = "${{ parameters.AssemblyVersionNumber }}"
      $minor = "${{ parameters.BuildVersionNumber }}"
      $buildId = [int]$(Build.BuildId)
      $assemblyBuild = $buildId % 65535
      $assemblyVersion = "$major.$minor.$assemblyBuild.0"

      Write-Host "##vso[task.setvariable variable=assemblyVersion]$assemblyVersion"
      Write-Host "Package Version: $(versionNumber)"
      Write-Host "Assembly Version: $assemblyVersion"
      Write-Host "Build Number: $(Build.BuildNumber)"

- task: NuGetToolInstaller@1
 
 
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
 
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/t:Rebuild /p:DeployOnBuild=True;DeployDefaultTarget=WebPublish;WebPublishMethod=FileSystem;DeleteExistingFiles=True;publishUrl=$(Build.ArtifactStagingDirectory)\Masterdata.SiteEditor /p:Version=$(versionNumber) /p:AssemblyVersion=$(assemblyVersion) /p:FileVersion=$(assemblyVersion)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
 
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
 
 
- task: ArchiveFiles@2
  displayName: 'Archive MasterData.SiteEditor'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.SiteEditor.zip'
    replaceExistingArchive: true
 
- publish: '$(Build.ArtifactStagingDirectory)/MasterData.SiteEditor.zip'
  displayName: 'Publish MasterData.SiteEditor.zip'
  artifact: SiteEditor

- task: ArchiveFiles@2
  displayName: 'Archive MasterData.SiteEditor.UpdateTool'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/MDSiteEditorUpdateTool/bin/Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MasterData.SiteEditor.UpdateTool.zip'
    replaceExistingArchive: true
 
- publish: '$(Build.ArtifactStagingDirectory)/MasterData.SiteEditor.UpdateTool.zip'
  displayName: 'Publish MasterData.SiteEditor.UpdateTool.zip'
  artifact: SiteEditorUpdateTool
